services:
  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile.dev
    restart: "no"
    environment:
      POLLING: ${POLLING:-false}
      VITE_API_URL: ${VITE_API_URL:-https://api.easymotion.devlocal}
    ports:
      # add variable in .env to change port
      - "${WEB_DEV_PORT:-8082}:5173"
    volumes:
      - .:/workspace:cached
    depends_on:
      api:
        condition: service_healthy
        # condition: service_started
    tty: true
    entrypoint: sh /workspace/webapp/entrypoint.sh
    command: npm run dev

  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    # restart: "no"
    ports:
      # add variable in .env to change port
      - "${API_DEV_PORT:-8081}:3000"
    volumes:
      - .:/workspace:cached
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SMTP_HOST: "mailhog"
      SMTP_PORT: 1025
      SMTP_SECURE: false
      JWT_SECRET: "KzSMuZlKyQcFk2haMuZ6x6rGq/wlHDZ8/+VS1YSQSIkw"
      JWT_AUDIENCE: "easymotion.dev"
      JWT_ISSUER: "api.easymotion.devlocal"
      JWT_EXPIRES_IN: "1800s"

    healthcheck:
      # Check if the API is up and running every 5 seconds for ~8 minutes
      test: ["CMD", "curl", "-f", "http://localhost:3000/swagger/json"]
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 5s
    # tty: true
    entrypoint: sh /workspace/api/entrypoint.sh
    command: npm run start:dev
    # command: pm2-runtime start 'npm run start:dev' --name api-dev && sleep infinity

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # add variable in .env to change port
      - "${PG_DEV_PORT:-5432}:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_started
      webapp:
        condition: service_started
    environment:
      CERT_PATH: "/certs"
      DOMAIN: "*.easymotion.devlocal"
    volumes:
      - "./nginx/dev.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/.ssl:/certs" # gitignored folder, contains dev ssl certificates
    ports:
      - 80:80
      - 443:443

  # Web-based PostgreSQL admin tool
  pgadmin:
    image: dpage/pgadmin4
    restart: "no"
    ports:
      # add variable in .env to change port
      - "${PG_ADMIN_PORT:-8083}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: db@easymotion.devlocal
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${MAIL_HOG_PORT:-8025}:8025"

volumes:
  pgdata:
  pgadmin_data:
