services:
  db:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      # add variable in .env to change port
      - "${PG_DEV_PORT:-5432}:5432"
    restart: always
    environment:
      POSTGRES_USER: easymotion
      POSTGRES_PASSWORD: easymotion
      POSTGRES_DB: easymotion

  nginx:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: nginx
      dockerfile: Dockerfile
    environment:
      CERT_PATH: "/certs"
    volumes:
      - "./nginx/dev.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/.ssl:/certs" # gitignored folder, contains dev ssl certificates
    ports:
      - "80:80"
      - "443:443"

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${MAIL_HOG_PORT:-8025}:8025"
      - "${MAIL_HOG_SMTP_PORT:-1025}:1025"

volumes:
  pgdata:
