services:
  webapp:
    image: ghcr.io/ingsw24/easymotion-webapp:${WEBAPP_VERSION:-latest}
    restart: "unless-stopped"
    environment:
      VITE_API_URL: ${VITE_API_URL:-https://api.easymotion.it}
    depends_on:
      api:
        condition: service_healthy
      db:
        condition: service_started

  api:
    build:
      image: ghcr.io/ingsw24/easymotion-api:${API_VERSION:-latest}
    restart: "unless-stopped"
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL}
    healthcheck:
      # Check if the API is up and running every 5 seconds for ~8 minutes
      test: ["CMD", "curl", "-f", "http://localhost:3000/swagger/json"]
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 5s

  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  nginx:
    image: nginx
    depends_on:
      api:
        condition: service_started
      webapp:
        condition: service_started
    volumes:
      - "./nginx/dev.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
      - 443:443

volumes:
  pgdata:
    external: true
