FROM node:20-alpine

RUN apk add --no-cache curl
RUN apk add --no-cache git
RUN apk add --no-cache zsh
RUN apk add --no-cache openssh
RUN apk add --no-cache neovim

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

RUN npm i -g @nestjs/cli

WORKDIR /workspace/webapp

ENV NODE_ENV=development
ENV SHELL=zsh
ENV EDITOR=nvim
