FROM node:20-alpine

RUN apk add --no-cache libc6-compat
RUN apk add --no-cache openssl
RUN apk add --no-cache openssh
RUN apk add --no-cache curl
RUN apk add --no-cache git
RUN apk add --no-cache zsh

RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

RUN npm i -g @nestjs/cli

COPY /entrypoint.sh entrypoint.sh
RUN sed -i 's/\r$//g' /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /workspace/api

ENV NODE_ENV=development
ENV SHELL=/bin/zsh
ENV EDITOR=nvim
ENV AUTO_INSTALL_DEPS=true

ENTRYPOINT [ "sh", "/entrypoint.sh" ]
