name: Build and Push WebApp Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-webapp:
    runs-on: ubuntu-latest

    env:
      VITE_API_URL: "${{ vars.VITE_API_URL }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push WebApp Docker image
        run: |
          IMAGE_NAME=ghcr.io/ingsw24/easymotion-webapp
          docker build --build-arg VITE_API_URL=$VITE_API_URL . --target webapp --tag $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
