name: Release Webapp

# Initial template for the release of the webapp
# This workflow will build a docker image and push it to the GitHub Container Registry
# This is not used for now, but it will be useful as a started in the future

on:
  push:
    tags:
      - "webapp-v*"
env:
  VITE_API_URL: "${{ vars.VITE_API_URL }}"
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          version=$(echo $GITHUB_REF_NAME | grep -o [0-9]\.*)
          cd webapp/
          docker build --build-arg VITE_API_URL=$VITE_API_URL . --tag ghcr.io/ingsw24/easymotion-webapp:$version
          docker push ghcr.io/ingsw24/easymotion-webapp:$version
