name: Build and Push API Docker Image

on:
  push:
    tags:
      - "v*"
      - "api-v*"

jobs:
  build-webapp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine environment
        id: determine_env
        run: |
          version=$(echo $GITHUB_REF_NAME | grep -o [0-9]\.*)
          echo "VERSION=${version}" >> $GITHUB_ENV

          if [[ "$version" == *"-beta" ]]; then
            echo "LATEST_TAG=latest-beta" >> $GITHUB_ENV
          else
            echo "LATEST_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and push WebApp Docker image
        run: |
          IMAGE_NAME=ghcr.io/ingsw24/easymotion-api

          # Build the image (version tag first)
          docker build \
            . \
            --target api \
            --tag $IMAGE_NAME:$VERSION \
            --tag $IMAGE_NAME:$LATEST_TAG

          # Push both tags
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:$LATEST_TAG
